### ISSUE TITLE
Can you share a example?

### ISSUE THREAD

**Issue by rayguan97** [NaokiAkai/mcl3d_ros#1]
Hi,

Can you give some more instruction on reproducing some localisation results? For example, which map / bag file we should use to reproduce some localization results, or share some simple demo.

**Comment by NaokiAkai** [comment]
You need to make a pcd file of your target environment first. Then, you need to make a distance field map that is a specfic format for mcl3d_ros. You can meke the distance map using pc_to_df.launch (see How to use of mcl3d_ros's README.md).

You can give the map mcl3d_ros using mcl.launch. mcl3d_ros works if you publish 3D LiDAR scan points.
